drop table "RAFFLE"."BOARD" cascade constraints PURGE;
drop table "RAFFLE"."MEMBER" cascade constraints PURGE;
drop table "RAFFLE"."RESELL_R" cascade constraints PURGE;
drop table "RAFFLE"."RLIST" cascade constraints PURGE;
drop table "RAFFLE"."RWINNING" cascade constraints PURGE;
drop table "RAFFLE"."SELL_R" cascade constraints PURGE;
drop table "RAFFLE"."SLIST" cascade constraints PURGE;
drop table "RAFFLE"."SWINNING" cascade constraints PURGE;
drop table "RAFFLE"."BOARD" cascade constraints PURGE;

--시퀀스도 삭제하고 다시 만들어주세요..ㅎ

CREATE TABLE MEMBER
    ( MEMBERNO NUMBER(10) PRIMARY KEY,
    USERID VARCHAR2(10) NOT NULL,
    PASSWD VARCHAR2(10) NOT NULL,
    USERNAME VARCHAR2(10) NOT NULL,
    NICKNAME VARCHAR2(100) NOT NULL,
    POST VARCHAR2(6) NOT NULL,
    ADDR1 VARCHAR2(500) NOT NULL,
    ADDR2 VARCHAR2(500) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    BIRTH VARCHAR2(10) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL
    );

CREATE TABLE RESELL_R
   (  RESELL_RNO NUMBER(6) PRIMARY KEY,
     MEMBERNO NUMBER(10),
     NICKNAME VARCHAR2(100) NOT NULL,
     RAFFLENAME VARCHAR2(50) NOT NULL,
     TOTAL_PRICE NUMBER(10) NOT NULL,
     ATTEND_AMOUNT NUMBER(3) NOT NULL,
     PER_PRICE NUMBER(10) NOT NULL,
     VIEWCNT NUMBER(10)
   );   
   
CREATE TABLE SELL_R
   (  SELL_RNO NUMBER(6) PRIMARY KEY,
     MEMBERNO NUMBER(10),
     NICKNAME VARCHAR2(100) NOT NULL,
     RAFFLENAME VARCHAR2(50) NOT NULL,
     RAFFLEPRICE NUMBER(10) NOT NULL,
     RAFFLEAMOUNT NUMBER(3) NOT NULL,
     DURATION NUMBER(2) NOT NULL,
     VIEWCNT NUMBER(10)
   );   
   
CREATE TABLE SSPOT
   ( SELL_RNO NUMBER(10),
      MEMBERNO NUMBER(10) ,
      RAFFLENAME VARCHAR2(20) NOT NULL,         
      USERNAME VARCHAR2(10) NOT NULL,
      NICKNAME VARCHAR2(100) NOT NULL,
      POST VARCHAR2(6) NOT NULL,
      ADDR1 VARCHAR2(500) NOT NULL,
      ADDR2 VARCHAR2(500) NOT NULL,
      PHONE VARCHAR2(20) NOT NULL,
      VIEWCNT NUMBER(10)
   );

CREATE TABLE RSPOT
   ( RESELL_RNO NUMBER(10),
      MEMBERNO NUMBER(10),
      RAFFLENAME VARCHAR2(20) NOT NULL,         
      USERNAME VARCHAR2(10) NOT NULL,
      NICKNAME VARCHAR2(100) NOT NULL,
      POST VARCHAR2(6) NOT NULL,
      ADDR1 VARCHAR2(500) NOT NULL,
      ADDR2 VARCHAR2(500) NOT NULL,
      PHONE VARCHAR2(20) NOT NULL,
      SPOT NUMBER(4) NOT NULL,
      VIEWCNT NUMBER(10)
   );
CREATE TABLE RWINNING
   ( RESELL_RNO NUMBER(10),
      NICKNAME VARCHAR2(100) NOT NULL,
      USERNAME VARCHAR2(10) NOT NULL,
      POST VARCHAR2(6) NOT NULL,
      ADDR1 VARCHAR2(500) NOT NULL,
      ADDR2 VARCHAR2(500) NOT NULL,
      PHONE VARCHAR2(20) NOT NULL
   );
CREATE TABLE SWINNING
   ( SELL_RNO NUMBER(10),
      NICKNAME VARCHAR2(100) NOT NULL,
      USERNAME VARCHAR2(10) NOT NULL,
      POST VARCHAR2(6) NOT NULL,
      ADDR1 VARCHAR2(500) NOT NULL,
      ADDR2 VARCHAR2(500) NOT NULL,
      PHONE VARCHAR2(20) NOT NULL
   );

CREATE TABLE NOTICE
   ( BNO NUMBER(10) PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    REGDATE DATE,
    VIEWCNT NUMBER(10)
   );

CREATE TABLE FORUM
   ( BNO NUMBER(10) PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    REGDATE DATE,
    VIEWCNT NUMBER(10)
   );
   
   ALTER TABLE SSPOT
ADD CONSTRAINT SSPOT_MEMBERNO_FK FOREIGN KEY(MEMBERNO)
REFERENCES MEMBER(MEMBERNO) ON DELETE CASCADE;
   
ALTER TABLE SSPOT
ADD CONSTRAINT SSPOT_SELL_RNO_FK FOREIGN KEY(SELL_RNO)
REFERENCES SELL_R(SELL_RNO) ON DELETE CASCADE;


ALTER TABLE RSPOT
ADD CONSTRAINT RSPOT_MEMBERNO_FK FOREIGN KEY(MEMBERNO)
REFERENCES MEMBER(MEMBERNO) ON DELETE CASCADE;
   
ALTER TABLE RSPOT
ADD CONSTRAINT RSPOT_RESELL_RNO_FK FOREIGN KEY(RESELL_RNO)
REFERENCES RESELL_R(RESELL_RNO) ON DELETE CASCADE;

ALTER TABLE RWINNING
ADD CONSTRAINT RWINNING_RESELL_RNO_FK FOREIGN KEY(RESELL_RNO)
REFERENCES RESELL_R(RESELL_RNO) ON DELETE CASCADE;

ALTER TABLE SWINNING
ADD CONSTRAINT SWINNING_SELL_RNO_FK FOREIGN KEY(SELL_RNO)
REFERENCES SELL_R(SELL_RNO) ON DELETE CASCADE;

-------------------------------------------------------------------------------------------------

ALTER TABLE RESELL_R ADD DEADLINE DATE;
ALTER TABLE RESELL_R ADD TEXT VARCHAR2(500) NOT NULL;
ALTER TABLE RESELL_R MODIFY DEADLINE NOT NULL;
ALTER TABLE RESELL_R MODIFY MEMBERNO NOT NULL;
ALTER TABLE RESELL_R MODIFY TOTAL_PRICE VARCHAR2(10);
ALTER TABLE RESELL_R MODIFY ATTEND_AMOUNT VARCHAR2(20);
ALTER TABLE RESELL_R MODIFY PER_PRICE VARCHAR2(10);


ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/RR HH:MI:SS';

ALTER TABLE SELL_R DROP COLUMN DURATION;
ALTER TABLE SELL_R ADD TEXT VARCHAR2(500) NOT NULL;
ALTER TABLE SELL_R ADD DEADLINE DATE;
ALTER TABLE SELL_R MODIFY DEADLINE NOT NULL;
ALTER TABLE SELL_R MODIFY RAFFLEPRICE VARCHAR2(10);
ALTER TABLE SELL_R MODIFY RAFFLEAMOUNT VARCHAR2(20);

ALTER TABLE NOTICE MODIFY REGDATE DEFAULT SYSDATE;
ALTER TABLE NOTICE MODIFY VIEWCNT DEFAULT 0;

ALTER TABLE FORUM MODIFY REGDATE DEFAULT SYSDATE;
ALTER TABLE FORUM MODIFY VIEWCNT DEFAULT 0;

CREATE SEQUENCE MEMBER_SEQ_MEMBERNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RESELL_R_SEQ_RESELL_RNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SELL_R_SEQ_SELL_RNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE FORUM_SEQ_BNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE NOTICE_SEQ_BNO INCREMENT BY 1 START WITH 1;

ALTER TABLE SSPOT MODIFY VIEWCNT DEFAULT 0;
ALTER TABLE RSPOT MODIFY VIEWCNT DEFAULT 0;

ALTER TABLE RESELL_R
ADD CONSTRAINT RESELL_R_RESELL_RNO_FK FOREIGN KEY(MEMBERNO)
REFERENCES MEMBER(MEMBERNO) ON DELETE CASCADE;

ALTER TABLE SELL_R
ADD CONSTRAINT SELL_R_MEMBERNO_FK FOREIGN KEY(MEMBERNO)
REFERENCES MEMBER(MEMBERNO) ON DELETE CASCADE;

ALTER TABLE SELL_R ADD IMAGE VARCHAR2(50);

UPDATE SELL_R SET IMAGE = 'img-pro-1' WHERE rafflename = '1201A664-021';
UPDATE SELL_R SET IMAGE = 'img-pro-2' WHERE rafflename = '307385-141';
UPDATE SELL_R SET IMAGE = 'img-pro-3' WHERE rafflename = '414571-167';
UPDATE SELL_R SET IMAGE = 'img-pro-4' WHERE rafflename = '555088-036';
UPDATE SELL_R SET IMAGE = 'img-pro-5' WHERE rafflename = 'AQ0818-148';
UPDATE SELL_R SET IMAGE = 'img-pro-6' WHERE rafflename = 'BB550WBG';
UPDATE SELL_R SET IMAGE = 'img-pro-7' WHERE rafflename = 'BQ6472-121';
UPDATE SELL_R SET IMAGE = 'img-pro-8' WHERE rafflename = 'BQ6817-602';
UPDATE SELL_R SET IMAGE = 'img-pro-9' WHERE rafflename = 'CP9652';
UPDATE SELL_R SET IMAGE = 'img-pro-10' WHERE rafflename = 'CT4142-710';
commit;

ALTER TABLE RESELL_R ADD IMAGE VARCHAR2(50);

UPDATE RESELL_R SET IMAGE = 'img-resell-1' WHERE rafflename = 'DC7294-103';
UPDATE RESELL_R SET IMAGE = 'img-resell-2' WHERE rafflename = 'FW4968';
UPDATE RESELL_R SET IMAGE = 'img-resell-3' WHERE rafflename = 'GZ6202';
UPDATE RESELL_R SET IMAGE = 'img-resell-4' WHERE rafflename = 'GZ6984';
UPDATE RESELL_R SET IMAGE = 'img-resell-5' WHERE rafflename = 'CT8529-410';
UPDATE RESELL_R SET IMAGE = 'img-resell-6' WHERE rafflename = 'DD1391-100';
UPDATE RESELL_R SET IMAGE = 'img-resell-7' WHERE rafflename = 'DO7216-100';
UPDATE RESELL_R SET IMAGE = 'img-resell-8' WHERE rafflename = 'DO9406-200';
UPDATE RESELL_R SET IMAGE = 'img-resell-9' WHERE rafflename = 'F36640';
UPDATE RESELL_R SET IMAGE = 'img-resell-10' WHERE rafflename = 'GZ1935';
UPDATE RESELL_R SET IMAGE = 'img-resell-11' WHERE rafflename = 'M992GR';
commit;

alter table forum
add memberno number(10) not null;
alter table forum
add constraint forum_memberno_fk foreign key(memberno) references member(memberno)on delete cascade;

alter table notice
add memberno number(10) not null;
alter table notice
add constraint notice_memberno_fk foreign key(memberno) references member(memberno)on delete cascade;